---
title: "Final Project"
output: html_document
author: Insert Your Name Here
---

```{r setup, include=FALSE}
library(plyr)
library(tidyverse)
library(readxl)
library(lubridate)
library("orcutt")
knitr::opts_chunk$set(cache=TRUE,
                      message=FALSE, warning=FALSE)
```

\vspace{0.5 in}

Politics looms large in many parts of American life, including in the financial markets.  The differences in policies and personnel associated with each candidate could affect the profitability of firms in different ways, with stocks potentially rising and falling with the expected outlooks for [Donald Trump](https://www.kiplinger.com/investing/stocks/stocks-to-buy/601637/best-stocks-to-buy-president-donald-trump-re-election) and [Joe Biden](https://www.kiplinger.com/investing/stocks/stocks-to-buy/601691/best-stocks-to-buy-for-the-joe-biden-presidency).

In this assignment, your team will analyze a set of around 30 stocks and indicate which, if any are most exposed to political factors.

You will work in teams of two or three people.  These teams will be sub-units of your assigned teams for the Spring 2021 term.  I will post a proposed team assignment on Canvas.  You may switch teams with mutual agreement of all involved subject to the condition that teams have no fewer than 2 people and no more than 3 people.

**For teams of 2 people**: you will analyze stock prices as a function of a single presidential candidate (Trump or Biden or another in the data set if you so wish). Your page limit is 4 pages.

**For teams of 3 people**: you will create analyze stock prices with two models - one for each of two candidates you select (for example, you could do one model for Trump and one model for Biden). Your page limit is 6 pages.

- The stock market data is in _stocks2020.csv_. This data includes daily closing prices for the selected stocks (listed by ticker symbol) and the overall market return for the Dow Jones Industrial Average as well.

- The expected outlook from the prediction market for each candidate is available in _USPres_2020_Price History By Market -Bulk.xlsx_ This is data from the PredictIt betting market in which investors buy shares in (among other things) presidential candidates.  Share are worth \$1 if the candidate wins the general election.  The price for a candidate on a given day is taken to be the market's estimate of the probability of victory for that candidate.

Some considerations you may wish to consider in your analysis:

- What dates are appropriate for each candidate? Are the results the same whether we include the major very major (and arguably nonsensical) changes on election day?
- How should we measure the variables? As levels? Or changes?
- What factors should we control for?

In the real world you would, of course, have very substantial latitude in how to undertake the analysis and present the results.  For the sake of setting expectations for this assignment, though, you will need to do the following:

1. Limit the total page of your pdf or html document to the page limited discussed above.

2. The RMarkdown should contain every step - from loading the data to producing the report.  Use RMarkdown chunk settings so that the R code is **not visible** in the final pdf/html output. You will submit both the RMarkdown file and the final output pdf/html file.

3. Include at least 1 and no more than 4 figures.  Each figure may have multiple panels.

4. Merge two (or more) data sets

5. Create at least one function

6. Implement at least two statistical models, presented as a table. Assume your audience is statistically experience enough that they can understand models presented as equations.

We will evaluate your project in terms of the following:

1. Quality of the analysis
2. Clarity of the explanation
3. Clarity/visual appeal of the figures
4. Quality of the R code (including documentation in the .Rmd file)
